apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic
  namespace: kube-system
spec:
  chart:
    spec:
      chart: elastic
      sourceRef:
        kind: HelmRepository
        name: elasticsearch
      version: '>=7.15.0'
  values: