apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: kube-system
spec:
  chart:
    spec:
      chart: kibana
      sourceRef:
        kind: HelmRepository
        name: elastic
      version: ">=7.15.0"
  interval: 1m0s
 
