apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openvpn
  namespace: kube-system
spec:
  chart: 
    spec:
      chart: openvpn
      sourceRef:
        kind: HelmRepository
        name: openvpn
        namespace: kube-system
      version: '>=0.1.1'
  interval: 1m0s
  values:
        
    host: https://balabenc.web.elte.hu/

    ui:
      enabled: false
      ssl:
        enabled: false
        secret: openvpn-letsencrypt-secret
        prod: false
        email: ""
      htmlConfigmap: default
      branding: "CloudPosse OpenVPN"

    oauth:
      app:
        # Common oauth configs
        clientID: d3ae6bf5e218441d5698
        clientSecret: 8c25e68b231aa2858d84cf902bcf0900513e364e

        # Github specific configs
        githubOrg: Balazs-Bence
        githubTeam: openvpn

        # Email filters
        emailDomains:
          - "*"
        emails:
        #      - admin@example.com

        skipAuthRegex:
        #  - ""

        # oAuth2 proxy configs
        requestLogging: false

        # oAuth2 proxy session cookie config
        cookieName:
        cookieSecret: REFoW0psd25dZk82WyMhWHM2W1UrVDdwWFNAQkNBKXs=
        cookieDomain: https://balabenc.web.elte.hu/
        cookieExpire:
        cookieRefresh:
        cookieHttponly: false

