apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: openvpn
  namespace: kube-system
spec:
  interval: 30m0s
  url: stable http://storage.googleapis.com/kubernetes-charts
