apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: openvpn
  namespace: kube-system
spec:
  interval: 30m0s
  url: https://github.com/jfelten/openvpn-docker
  url: https://github.com/kubernetes/charts/tree/master/stable/openvpn
  url: https://github.com/jfelten/helm-charts
