apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openvpn
  namespace: kube-system
spec:
  chart: 
    spec:
      chart: cloudposse
      sourceRef:
        kind: HelmRepository
        name: openvpn
        namespace: kube-system
      version: '>=0.1.1'
  interval: 1m0s
  values:
        
    host: *HOSTNAME

    ui:
      ssl:
        enabled: false
        secret: openvpn-letsencrypt-secret
        prod: false
        email: ""
      htmlConfigmap: default
      branding: "CloudPosse OpenVPN"

    persistence:
      enabled: true
      storageClass: default
      accessMode: ReadWriteMany
      size: 1Gi

    easyrsa:
      vars:
        EASYRSA_REQ_COUNTRY: "US"
        EASYRSA_REQ_PROVINCE: "California"
        EASYRSA_REQ_CITY: "San Francisco"
        EASYRSA_REQ_ORG: "Copyleft Certificate Co"
        EASYRSA_REQ_EMAIL: "me@example.net"
        EASYRSA_REQ_OU: "My Organizational Unit"
        EASYRSA_CA_EXPIRE: "3650"
        EASYRSA_CERT_EXPIRE: "30"
        EASYRSA_CRL_DAYS: "180"

    debug: 0

    openvpn:
      env:
        OVPN_RENEG_SEC: 0
      #push:
      #- "dhcp-option DOMAIN cloudposse.com"
      replicaCount: 1
      image:
        repository: cloudposse/openvpn
        tag: latest
        pullPolicy: Always
      service:
        name: openvpn
        type: LoadBalancer
        externalPort: 80
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    proxy:
      image:
        repository: nginx
        tag: alpine
        pullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    ssl_terminator:
      replicaCount: 1
      image:
        repository: ployst/nginx-ssl-proxy
        tag: 0.0.7
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        http:
          name: http
          externalPort: 80
        https:
          name: https
          externalPort: 443
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    letsencrypt:
      replicaCount: 1
      image:
        repository: cloudposse/letsencrypt
        tag: latest
        pullPolicy: Always
      service:
        name: nginx
        type: ClusterIP
        externalPort: 80
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    dashboard:
      image:
        repository: nginx
        tag: alpine
        pullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi

    oauth:
      app:
        # Common oauth configs
        clientID: d3ae6bf5e218441d5698
        clientSecret: 8c25e68b231aa2858d84cf902bcf0900513e364e

        # Github specific configs
        githubOrg: Balazs-Bence
        githubTeam: openvpn

        # Email filters
        emailDomains:
          - "*"
        emails:
        #      - admin@example.com

        skipAuthRegex:
        #  - ""

        # oAuth2 proxy configs
        requestLogging: false

        # oAuth2 proxy session cookie config
        cookieName:
        cookieSecret: REFoW0psd25dZk82WyMhWHM2W1UrVDdwWFNAQkNBKXs=
        cookieDomain: test.com
        cookieExpire:
        cookieRefresh:
        cookieHttponly: false

      image:
        repository: cloudposse/oauth2-proxy
        tag: latest
        pullPolicy: Always
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
