apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openvpn
  namespace: kube-system
spec:
  chart: 
    spec:
      chart: incubator
      sourceRef:
        kind: HelmRepository
        name: openvpn
        namespace: kube-system
      version: '>=0.1.1'
  interval: 1m0s
  values:
    host: test.com
    
